import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import './font.css'
import { FC } from 'react'
import { WrapperTypes } from '@/utils/types'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const RootLayout: FC<WrapperTypes> = ({ children }) => {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='h-screen grid place-content-center'>
          {children}
        </div>
      </body>
    </html>
  )
}

export default RootLayout;